{
 "title": "Quota Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Compute Quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "compute_page_quotas / compute_page_limits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "storage_page_quotas / storage_page_limits"
    }
   ]
  },
  {
   "title": "Arm Quotas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "arm_page_quotas / arm_page_limits"
    }
   ]
  },
  {
   "title": "Network Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "network_page_quotas / (network_page_limits > 5)"
    }
   ]
  },
  {
   "title": "Role Assignment Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "role_assignment_page_quotas / role_assignment_page_limits"
    }
   ]
  }
 ]
}